/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.codewithaj.reckoner;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author ANARI BEBE PATRICK
 */
public class ModernSimpleJFrame extends javax.swing.JFrame {

    /**
     * Creates new form ModernSimpleJFrame
     */
    public ModernSimpleJFrame() {
        initComponents();
    }
      double answer;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        rLabel = new javax.swing.JLabel();
        fField = new javax.swing.JTextField();
        sField = new javax.swing.JTextField();
        AQ = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        PreAQ = new javax.swing.JLabel();
        miusPanel = new javax.swing.JPanel();
        miusLabel = new javax.swing.JLabel();
        plusPanel = new javax.swing.JPanel();
        plusLabel = new javax.swing.JLabel();
        multiPanel = new javax.swing.JPanel();
        multiLabel = new javax.swing.JLabel();
        divPanel = new javax.swing.JPanel();
        divLabel = new javax.swing.JLabel();
        modPanel = new javax.swing.JPanel();
        modLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        clearLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(102, 0, 255));

        jLabel1.setFont(new java.awt.Font("Felix Titling", 2, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("THE RECKONER");

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ANARI BEBE PATRICK\\Desktop\\GUIPics\\anonymous-mask2.png")); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("ADDING PACE TO YOUR WORK");

        jLabel28.setBackground(new java.awt.Color(255, 255, 255));
        jLabel28.setFont(new java.awt.Font("Vivaldi", 2, 16)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Basic calculator for simple calculations,");

        jLabel29.setBackground(new java.awt.Color(255, 255, 255));
        jLabel29.setFont(new java.awt.Font("Vivaldi", 2, 16)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("such as addition ,sutraction,");

        jLabel30.setBackground(new java.awt.Color(255, 255, 255));
        jLabel30.setFont(new java.awt.Font("Vivaldi", 2, 16)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("multiplication, division and");

        jLabel31.setBackground(new java.awt.Color(255, 255, 255));
        jLabel31.setFont(new java.awt.Font("Vivaldi", 2, 16)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("modulus.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel3)))
                .addGap(20, 20, 20))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel30)
                            .addComponent(jLabel31)
                            .addComponent(jLabel28)
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel31)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\ANARI BEBE PATRICK\\Desktop\\GUIPics\\bmo.png")); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText(" SIMPLE CALCULATOR WITH MEMORY FEATURE");

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel10.setText("FIRST NUMBER");
        jLabel10.setToolTipText("ENTER YOUR PRINCIPAL");

        jLabel20.setBackground(new java.awt.Color(0, 0, 0));
        jLabel20.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel20.setText("SECOND NUMBER");
        jLabel20.setToolTipText("ANNUAL INTEREST ");

        rLabel.setBackground(new java.awt.Color(0, 0, 0));
        rLabel.setFont(new java.awt.Font("Tempus Sans ITC", 1, 48)); // NOI18N
        rLabel.setText("RESULT");
        rLabel.setToolTipText("THIS IS YOUR AQUIRED INVESTMENT");

        sField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sFieldActionPerformed(evt);
            }
        });

        AQ.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 50)); // NOI18N
        AQ.setForeground(new java.awt.Color(51, 51, 51));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel7.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel7.setText("<< RESULT");

        PreAQ.setFont(new java.awt.Font("Tw Cen MT Condensed", 3, 16)); // NOI18N
        PreAQ.setForeground(new java.awt.Color(51, 51, 51));

        miusPanel.setBackground(new java.awt.Color(204, 204, 204));
        miusPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                miusPanelMouseClicked(evt);
            }
        });

        miusLabel.setFont(new java.awt.Font("Tempus Sans ITC", 1, 48)); // NOI18N
        miusLabel.setForeground(new java.awt.Color(51, 51, 51));
        miusLabel.setText("-");
        miusLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                miusLabelMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                miusLabelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                miusLabelMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout miusPanelLayout = new javax.swing.GroupLayout(miusPanel);
        miusPanel.setLayout(miusPanelLayout);
        miusPanelLayout.setHorizontalGroup(
            miusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(miusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(miusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        miusPanelLayout.setVerticalGroup(
            miusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(miusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        plusPanel.setBackground(new java.awt.Color(204, 204, 204));
        plusPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                plusPanelMouseClicked(evt);
            }
        });

        plusLabel.setFont(new java.awt.Font("Tempus Sans ITC", 1, 48)); // NOI18N
        plusLabel.setForeground(new java.awt.Color(51, 51, 51));
        plusLabel.setText("+");
        plusLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                plusLabelMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                plusLabelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                plusLabelMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout plusPanelLayout = new javax.swing.GroupLayout(plusPanel);
        plusPanel.setLayout(plusPanelLayout);
        plusPanelLayout.setHorizontalGroup(
            plusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(plusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        plusPanelLayout.setVerticalGroup(
            plusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(plusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        multiPanel.setBackground(new java.awt.Color(204, 204, 204));
        multiPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                multiPanelMouseClicked(evt);
            }
        });

        multiLabel.setFont(new java.awt.Font("Tempus Sans ITC", 1, 25)); // NOI18N
        multiLabel.setForeground(new java.awt.Color(51, 51, 51));
        multiLabel.setText("*");
        multiLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                multiLabelMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                multiLabelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                multiLabelMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout multiPanelLayout = new javax.swing.GroupLayout(multiPanel);
        multiPanel.setLayout(multiPanelLayout);
        multiPanelLayout.setHorizontalGroup(
            multiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(multiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(multiLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        multiPanelLayout.setVerticalGroup(
            multiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(multiLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        divPanel.setBackground(new java.awt.Color(204, 204, 204));
        divPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                divPanelMouseClicked(evt);
            }
        });

        divLabel.setFont(new java.awt.Font("Tempus Sans ITC", 1, 25)); // NOI18N
        divLabel.setForeground(new java.awt.Color(51, 51, 51));
        divLabel.setText("/");
        divLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                divLabelMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                divLabelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                divLabelMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout divPanelLayout = new javax.swing.GroupLayout(divPanel);
        divPanel.setLayout(divPanelLayout);
        divPanelLayout.setHorizontalGroup(
            divPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(divPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(divLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        divPanelLayout.setVerticalGroup(
            divPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(divLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        modPanel.setBackground(new java.awt.Color(204, 204, 204));
        modPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modPanelMouseClicked(evt);
            }
        });

        modLabel.setFont(new java.awt.Font("Tempus Sans ITC", 1, 25)); // NOI18N
        modLabel.setForeground(new java.awt.Color(51, 51, 51));
        modLabel.setText("%");
        modLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modLabelMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                modLabelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                modLabelMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout modPanelLayout = new javax.swing.GroupLayout(modPanel);
        modPanel.setLayout(modPanelLayout);
        modPanelLayout.setHorizontalGroup(
            modPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(modLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        modPanelLayout.setVerticalGroup(
            modPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(modLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel3MouseReleased(evt);
            }
        });

        clearLabel.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        clearLabel.setForeground(new java.awt.Color(51, 51, 51));
        clearLabel.setText("CLEAR");
        clearLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearLabelMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                clearLabelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clearLabelMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(clearLabel)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(clearLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(jLabel10))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel20)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(AQ, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(rLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(fField, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sField, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(plusPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(divPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(miusPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(multiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(modPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(70, 70, 70))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(PreAQ, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(115, 115, 115))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(plusPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(miusPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(sField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel20))
                            .addComponent(multiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(divPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(rLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AQ, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21))
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(modPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PreAQ, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sFieldActionPerformed

    private void miusLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miusLabelMouseClicked
         try{
        double firstNumber = 0, secondNumber = 0;
       
       firstNumber = Integer.parseInt(fField.getText());
       secondNumber = Integer.parseInt(sField.getText());
       
     answer= firstNumber - secondNumber;
       
       rLabel.setText(String.valueOf(answer));
       JOptionPane.showMessageDialog(null,"DONE!!", "MESSAGE", JOptionPane.PLAIN_MESSAGE);
       }catch(Exception e){
             JOptionPane.showMessageDialog(null, "Text field cotains an invalid character","ERROR",JOptionPane.PLAIN_MESSAGE);
       }

    }//GEN-LAST:event_miusLabelMouseClicked

    private void miusLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miusLabelMousePressed
        miusPanel.setBackground(new Color(255,204,204));
    }//GEN-LAST:event_miusLabelMousePressed

    private void miusLabelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miusLabelMouseReleased
        miusPanel.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_miusLabelMouseReleased

    private void miusPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miusPanelMouseClicked

        //calculatePanel.setBackground(new Color(255,204,204));
    }//GEN-LAST:event_miusPanelMouseClicked

    private void plusLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plusLabelMouseClicked
        try{
        double firstNumber = 0, secondNumber = 0;
       
       firstNumber = Integer.parseInt(fField.getText());
       secondNumber = Integer.parseInt(sField.getText());
       
      answer = firstNumber + secondNumber;
       
       rLabel.setText(String.valueOf(answer));
       JOptionPane.showMessageDialog(null,"DONE!!", "MESSAGE", JOptionPane.PLAIN_MESSAGE);
       }catch(Exception e){
             JOptionPane.showMessageDialog(null, "Text field cotains an invalid character","ERROR",JOptionPane.PLAIN_MESSAGE);
       }
    }//GEN-LAST:event_plusLabelMouseClicked

    private void plusLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plusLabelMousePressed
          plusPanel.setBackground(new Color(255,204,204));
    }//GEN-LAST:event_plusLabelMousePressed

    private void plusLabelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plusLabelMouseReleased
         plusPanel.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_plusLabelMouseReleased

    private void plusPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plusPanelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_plusPanelMouseClicked

    private void multiLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_multiLabelMouseClicked
         try{
        double firstNumber = 0, secondNumber = 0;
       
       firstNumber = Integer.parseInt(fField.getText());
       secondNumber = Integer.parseInt(sField.getText());
       
      answer = firstNumber * secondNumber;
       
       rLabel.setText(String.valueOf(answer));
       JOptionPane.showMessageDialog(null,"DONE!!", "MESSAGE", JOptionPane.PLAIN_MESSAGE);
       
       }catch(Exception e){
             JOptionPane.showMessageDialog(null, "Text field cotains an invalid character","ERROR",JOptionPane.PLAIN_MESSAGE);
       }
    }//GEN-LAST:event_multiLabelMouseClicked

    private void multiLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_multiLabelMousePressed
          multiPanel.setBackground(new Color(255,204,204));
    }//GEN-LAST:event_multiLabelMousePressed

    private void multiLabelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_multiLabelMouseReleased
       multiPanel.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_multiLabelMouseReleased

    private void multiPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_multiPanelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_multiPanelMouseClicked

    private void divLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_divLabelMouseClicked
        try{
        double firstNumber = 0, secondNumber = 0;
       
       firstNumber = Integer.parseInt(fField.getText());
       secondNumber = Integer.parseInt(sField.getText());
       
        answer =  (float)firstNumber / (float)secondNumber;
       if(secondNumber ==0){
           answer =0;
       }
       rLabel.setText(String.valueOf(answer));
       JOptionPane.showMessageDialog(null,"DONE!!", "MESSAGE", JOptionPane.PLAIN_MESSAGE);
      
        }catch(Exception e){
             JOptionPane.showMessageDialog(null, "Text field cotains an invalid character","ERROR",JOptionPane.PLAIN_MESSAGE);
       }
    }//GEN-LAST:event_divLabelMouseClicked

    private void divLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_divLabelMousePressed
        divPanel.setBackground(new Color(255,204,204));
    }//GEN-LAST:event_divLabelMousePressed

    private void divLabelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_divLabelMouseReleased
       divPanel.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_divLabelMouseReleased

    private void divPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_divPanelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_divPanelMouseClicked

    private void modLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modLabelMouseClicked
       try{
        double firstNumber = 0, secondNumber = 0;
       
       firstNumber = Integer.parseInt(fField.getText());
       secondNumber = Integer.parseInt(sField.getText());
       
       
       answer= firstNumber % secondNumber;
       
       rLabel.setText(String.valueOf(answer));
       JOptionPane.showMessageDialog(null,"DONE!!", "MESSAGE", JOptionPane.PLAIN_MESSAGE);
           }catch(Exception e){
             JOptionPane.showMessageDialog(null, "Text field cotains an invalid character","ERROR",JOptionPane.PLAIN_MESSAGE);
       }
    }//GEN-LAST:event_modLabelMouseClicked

    private void modLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modLabelMousePressed
           modPanel.setBackground(new Color(255,204,204));
    }//GEN-LAST:event_modLabelMousePressed

    private void modLabelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modLabelMouseReleased
       modPanel.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_modLabelMouseReleased

    private void modPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modPanelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_modPanelMouseClicked

    private void clearLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearLabelMouseClicked
        fField.setText("");
        sField.setText("");
        AQ.setText("");
        PreAQ.setText(String.valueOf(answer));
        JOptionPane.showMessageDialog(null,"Field Cleared!!");
    }//GEN-LAST:event_clearLabelMouseClicked

    private void clearLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearLabelMousePressed
         jPanel3.setBackground(new Color(153,204,153)); 
    }//GEN-LAST:event_clearLabelMousePressed

    private void clearLabelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearLabelMouseReleased
          jPanel3.setBackground(new Color(204,204,204)); 
    }//GEN-LAST:event_clearLabelMouseReleased

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
     
          jPanel3.setBackground(new Color(153,255,153));
    }//GEN-LAST:event_jPanel3MousePressed

    private void jPanel3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseReleased
   jPanel3.setBackground(new Color(204,204,204));        
    }//GEN-LAST:event_jPanel3MouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModernSimpleJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModernSimpleJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModernSimpleJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModernSimpleJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModernSimpleJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AQ;
    private javax.swing.JLabel PreAQ;
    private javax.swing.JLabel clearLabel;
    private javax.swing.JLabel divLabel;
    private javax.swing.JPanel divPanel;
    private javax.swing.JTextField fField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel miusLabel;
    private javax.swing.JPanel miusPanel;
    private javax.swing.JLabel modLabel;
    private javax.swing.JPanel modPanel;
    private javax.swing.JLabel multiLabel;
    private javax.swing.JPanel multiPanel;
    private javax.swing.JLabel plusLabel;
    private javax.swing.JPanel plusPanel;
    private javax.swing.JLabel rLabel;
    private javax.swing.JTextField sField;
    // End of variables declaration//GEN-END:variables
}
